ALTER TABLE users ADD COLUMN created_at TIMESTAMP;
ALTER TABLE goal ADD COLUMN created_at TIMESTAMP;
ALTER TABLE tag ADD COLUMN created_at TIMESTAMP;
ALTER TABLE routine ADD COLUMN created_at TIMESTAMP;
ALTER TABLE todo ADD COLUMN created_at TIMESTAMP;
ALTER TABLE failure_reason ADD COLUMN created_at TIMESTAMP;

ALTER TABLE todo ALTER COLUMN is_pinned SET DEFAULT false;
